theme: jekyll-theme-slate
title: "Hyde Park COVID-19 Resource Outreach"
description: "A mutual aid effort supporting Hyde Park, Chicago and the surrounding communities."
show_downloads: false
github:
  is_project_page: false
